import { readFileSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { unzipSync } from "fflate";
import { docxToHtml, htmlToDocx } from "../adapters/docx/index";
import { odtToHtml, htmlToOdt } from "../adapters/odt/index";

// The passthrough guarantee, tested directly.
//
// richdoc's central claim is that anything the reader does not model survives byte for
// byte, and that an edit touches only what it has to. Until now the only real-file test
// asserted that the TEXT came back, which a writer could satisfy while quietly rewriting
// every part of the archive.
//
// So this asks two harder questions of every fixture:
//   1. no-edit identity  - read and write back with no edit; which parts changed at all?
//   2. blast radius      - change one paragraph; does anything outside the body move?
//
// The corpus is generated by scripts/gen-corpus.mjs and committed, so the inputs are
// byte-stable: regenerating them per run would compare a file against a different file.

const CORPUS = join(__dirname, "../../test-corpus");
const has = existsSync(CORPUS);
const fixtures = (ext: string): string[] =>
  has ? readdirSync(CORPUS).filter((f) => f.endsWith(ext)).sort() : [];

const read = (name: string): Uint8Array => new Uint8Array(readFileSync(join(CORPUS, name)));
const parts = (bytes: Uint8Array): Record<string, Uint8Array> => unzipSync(bytes);

const same = (a: Uint8Array | undefined, b: Uint8Array | undefined): boolean => {
  if (!a || !b || a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
  return true;
};

/** Paths whose bytes differ between two archives, plus any added or removed. */
function changedParts(before: Uint8Array, after: Uint8Array): string[] {
  const [a, b] = [parts(before), parts(after)];
  const names = new Set([...Object.keys(a), ...Object.keys(b)]);
  return [...names].filter((n) => !same(a[n], b[n])).sort();
}

// Parts a no-edit save is allowed to rewrite. The body is re-serialised from the parsed
// DOM whether or not anything changed, and the two settings parts carry state the editor
// normalises on load. Everything else must come back untouched: styles, numbering, fonts,
// themes, images, headers, footers, comments, notes, and every relationship part.
const DOCX_ALLOWED = new Set(["word/document.xml", "word/settings.xml", "[Content_Types].xml"]);
const ODT_ALLOWED = new Set(["content.xml", "settings.xml", "mimetype", "META-INF/manifest.xml", "meta.xml"]);

describe.skipIf(!has)("docx no-edit identity", () => {
  for (const name of fixtures(".docx")) {
    it(`rewrites only the body of ${name}`, () => {
      const original = read(name);
      const out = htmlToDocx(docxToHtml(original), original);
      const unexpected = changedParts(original, out).filter((p) => !DOCX_ALLOWED.has(p));
      expect(unexpected).toEqual([]);
    });
  }
});

describe.skipIf(!has)("odt no-edit identity", () => {
  for (const name of fixtures(".odt")) {
    it(`rewrites only the body of ${name}`, () => {
      const original = read(name);
      const out = htmlToOdt(odtToHtml(original), original);
      const unexpected = changedParts(original, out).filter((p) => !ODT_ALLOWED.has(p));
      expect(unexpected).toEqual([]);
    });
  }
});

// Saving repeatedly must reach a fixed point. This is the general form of a bug the
// no-edit check found: the docx writer minted a fresh hyperlink relationship on every
// save instead of reusing the existing one, so a document saved N times carried N
// identical relationships. Nothing may grow without bound just because a file was opened
// and saved again.
describe.skipIf(!has)("docx repeated saves reach a fixed point", () => {
  for (const name of fixtures(".docx")) {
    it(`stops changing ${name} after the first save`, () => {
      const once = htmlToDocx(docxToHtml(read(name)), read(name));
      const twice = htmlToDocx(docxToHtml(once), once);
      const thrice = htmlToDocx(docxToHtml(twice), twice);
      expect(changedParts(once, twice)).toEqual([]);
      expect(changedParts(twice, thrice)).toEqual([]);
    });
  }
});

describe.skipIf(!has)("odt repeated saves reach a fixed point", () => {
  for (const name of fixtures(".odt")) {
    it(`stops changing ${name} after the first save`, () => {
      const once = htmlToOdt(odtToHtml(read(name)), read(name));
      const twice = htmlToOdt(odtToHtml(once), once);
      const thrice = htmlToOdt(odtToHtml(twice), twice);
      expect(changedParts(once, twice)).toEqual([]);
      expect(changedParts(twice, thrice)).toEqual([]);
    });
  }
});

/** Replace the text of the first paragraph in the editable HTML, leaving the rest alone. */
function editFirstParagraph(html: string): string {
  const doc = new DOMParser().parseFromString(`<div>${html}</div>`, "text/html");
  const root = doc.body.firstElementChild!;
  for (const p of Array.from(root.querySelectorAll("p"))) {
    if ((p.textContent ?? "").trim().length < 3) continue;
    p.textContent = "EDITED PARAGRAPH TEXT";
    return root.innerHTML;
  }
  throw new Error("no paragraph with text to edit");
}

describe.skipIf(!has)("docx edit blast radius", () => {
  for (const name of fixtures(".docx")) {
    it(`confines a one-paragraph edit in ${name} to the body`, () => {
      const original = read(name);
      const html = docxToHtml(original);
      const out = htmlToDocx(editFirstParagraph(html), original);
      const unexpected = changedParts(original, out).filter((p) => !DOCX_ALLOWED.has(p));
      expect(unexpected).toEqual([]);
      // And the edit really happened, so an inert writer cannot pass this by doing nothing.
      expect(docxToHtml(out)).toContain("EDITED PARAGRAPH TEXT");
    });
  }
});

describe.skipIf(!has)("odt edit blast radius", () => {
  for (const name of fixtures(".odt")) {
    it(`confines a one-paragraph edit in ${name} to the body`, () => {
      const original = read(name);
      const html = odtToHtml(original);
      const out = htmlToOdt(editFirstParagraph(html), original);
      const unexpected = changedParts(original, out).filter((p) => !ODT_ALLOWED.has(p));
      expect(unexpected).toEqual([]);
      expect(odtToHtml(out)).toContain("EDITED PARAGRAPH TEXT");
    });
  }
});
